project_id = "tallyrec"

[api]
enabled = true
port = 54321
schemas = ["public", "app", "auth"]
extra_search_path = ["public", "app", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15
